---
- name: Install Auto Upgrade Ubuntu
  apt:
      name: "{{ packages }}"
      state: latest
  vars:
    packages:
      - unattended-upgrades
- name: Checking service
  command: sudo systemctl status "{{ item }}"
  with_items:
  - firewalld
  - ssh
  - unattended-upgrades
  register: result
  ignore_errors: yes
  
- name: showing report
  debug:
    var: result.stdout



  


