---
  #tasks file for ansible-pritunl
  

- name: Install Modul Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    allow_unauthenticated: yes
  vars:
    packages:
      - autoconf               
      - automake
      - pkg-config
      - libgtk-3-dev
      - autogen
      - libfm4
      - autopoint
      - gtk-doc-tools
      - dh-autoreconf
      - intltool
      - libnma-dev
      - libsecret-1-dev
      - git
      - curl   
  become: yes

- name: Clone From Github
  shell: git clone https://github.com/max-moser/network-manager-wireguard.git /tmp/network-manager-wireguard

- name: Change Permissions
  shell: sudo chmod -R 777 /tmp/network-manager-wireguard/ && sudo chown -R "{{ ansible_user }}":"{{ ansible_user }}" /tmp/network-manager-wireguard/
- name: Install Wireguard Network Manager
  command: sudo {{ item }} chdir="/tmp/network-manager-wireguard"
  with_items:
    - ./autogen.sh --without-libnm-glib
    - ./configure --without-libnm-glib --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/NetworkManager --localstatedir=/var
    - make
    - make install
